const $=s=>document.querySelector(s);let state=JSON.parse(localStorage.getItem('growvault-demo')||'{"spendable":0,"vaulted":0,"tx":[]}');
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(n);
function save(){localStorage.setItem('growvault-demo',JSON.stringify(state))}
function audit(entry){const expected=+(entry.gross*entry.rate).toFixed(2);return Math.abs(expected-entry.vault)<0.01?'VERIFIED':'REVIEW'}
function render(){let goal=+$('#goal').value;$('#spendable').textContent=money(state.spendable);$('#vaulted').textContent=money(state.vaulted);$('#goalLabel').textContent=money(goal);$('#goalBar').style.width=Math.min(100,state.vaulted/goal*100)+'%';const rate=+$('#rate').value/100;$('#projection').textContent=state.vaulted>=goal?'Milestone reached. Set the next target.':`At the current ${Math.round(rate*100)}% rule, about ${money((goal-state.vaulted)/rate)} of future deposits would fully fund this goal.`;$('#ledger').innerHTML=state.tx.slice().reverse().slice(0,8).map(t=>`<div class="tx"><div><strong>${t.type}</strong><br><small>${new Date(t.time).toLocaleString()}</small></div><div>${t.type==='Deposit'?money(t.gross):'-'+money(t.gross)}</div><div class="${t.audit==='VERIFIED'?'good':'audit'}">Watch-Dawg: ${t.audit}</div></div>`).join('')||'<div class="fine">No transactions yet. Run your first deposit.</div>'}
function syncLabels(){$('#depositValue').textContent=money(+$('#deposit').value);$('#rateValue').textContent=$('#rate').value+'%';render()}
$('#deposit').oninput=syncLabels;$('#rate').oninput=syncLabels;$('#goal').onchange=render;
$('#add').onclick=()=>{const gross=+$('#deposit').value,rate=+$('#rate').value/100,vault=+(gross*rate).toFixed(2),spend=+(gross-vault).toFixed(2);const entry={type:'Deposit',gross,rate,vault,spend,time:Date.now()};entry.audit=audit(entry);state.vaulted+=vault;state.spendable+=spend;state.tx.push(entry);save();render()};
$('#spend').onclick=()=>{const gross=Math.min(40,state.spendable);if(!gross)return alert('Add a deposit first.');state.spendable-=gross;state.tx.push({type:'Purchase',gross,rate:0,vault:0,spend:gross,time:Date.now(),audit:'VERIFIED'});save();render()};
$('#reset').onclick=()=>{state={spendable:0,vaulted:0,tx:[]};save();render()};
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});syncLabels();