const $=s=>document.querySelector(s);
const emptyState=()=>({spendable:0,vaulted:0,tx:[]});
function loadState(){try{const raw=localStorage.getItem('growvault-demo');if(!raw)return emptyState();const parsed=JSON.parse(raw);if(!parsed||!Number.isFinite(+parsed.spendable)||!Number.isFinite(+parsed.vaulted)||!Array.isArray(parsed.tx))return emptyState();return {spendable:+parsed.spendable,vaulted:+parsed.vaulted,tx:parsed.tx}}catch{return emptyState()}}
let state=loadState();
const round=n=>Math.round(Number(n)*100)/100;
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(Number(n)||0);
function save(){localStorage.setItem('growvault-demo',JSON.stringify(state))}
function applies(trigger,event){return trigger==='both'||trigger===event}
function audit(entry){if(entry.type==='Deposit'){const expectedVault=round(entry.gross*entry.rate);const expectedSpend=round(entry.gross-entry.vault);return Math.abs(expectedVault-entry.vault)<0.01&&Math.abs(expectedSpend-entry.spend)<0.01?'VERIFIED':'REVIEW'}if(entry.type==='Purchase'){const expectedVault=round(entry.gross*entry.rate);const expectedOutflow=round(entry.gross+expectedVault);return Math.abs(expectedVault-entry.vault)<0.01&&Math.abs(expectedOutflow-entry.spend)<0.01?'VERIFIED':'REVIEW'}return 'REVIEW'}
function playSpend(){return round(state.tx.filter(t=>t.type==='Purchase').reduce((sum,t)=>sum+(Number(t.gross)||0),0))}
function render(){const goal=Math.max(1,+$('#goal').value||1000);const rate=(+$('#rate').value||0)/100;const budget=Math.max(1,+$('#guard').value||100);const spent=playSpend();const remaining=round(budget-spent);$('#spendable').textContent=money(state.spendable);$('#vaulted').textContent=money(state.vaulted);$('#goalLabel').textContent=money(goal);$('#goalBar').style.width=Math.min(100,Math.max(0,state.vaulted/goal*100))+'%';$('#projection').textContent=state.vaulted>=goal?'Milestone reached. Set the next target.':rate>0?'At the current '+Math.round(rate*100)+'% rule, about '+money((goal-state.vaulted)/rate)+' of future rule-triggering dollars would fully fund this goal.':'Choose a Vault Rule above 0% to see a projection.';const guard=$('#guardStatus');guard.className='guard '+(remaining<0?'over':remaining<=budget*.2?'near':'');guard.innerHTML=remaining<0?'<strong>Budget reached</strong><br><small>'+money(spent)+' simulated discretionary spending against your '+money(budget)+' limit. Pause and decide whether the next purchase still fits your plan.</small>':'<strong>'+money(remaining)+' remaining</strong><br><small>'+money(spent)+' simulated discretionary spending against your '+money(budget)+' self-set spending boundary.</small>';$('#ledger').innerHTML=state.tx.slice().reverse().slice(0,8).map(t=>{const amount=t.type==='Deposit'?money(t.gross):'-'+money(Number.isFinite(+t.spend)?+t.spend:+t.gross);const detail=t.type==='Purchase'&&+t.vault>0?'<small>'+money(t.gross)+' purchase + '+money(t.vault)+' vaulted</small>':'';return '<div class="tx"><div><strong>'+t.type+'</strong><br><small>'+new Date(t.time).toLocaleString()+'</small>'+detail+'</div><div>'+amount+'</div><div class="'+(t.audit==='VERIFIED'?'good':'audit')+'">Watch-Dawg: '+t.audit+'</div></div>'}).join('')||'<div class="fine">No transactions yet. Run your first deposit.</div>'}
function syncLabels(){$('#depositValue').textContent=money(+$('#deposit').value);$('#rateValue').textContent=$('#rate').value+'%';render()}
$('#deposit').oninput=syncLabels;$('#rate').oninput=syncLabels;$('#goal').onchange=render;$('#trigger').onchange=render;$('#guard').onchange=render;
$('#add').onclick=()=>{const gross=round(+$('#deposit').value),baseRate=(+$('#rate').value||0)/100,rate=applies($('#trigger').value,'deposit')?baseRate:0,vault=round(gross*rate),spend=round(gross-vault);if(!(gross>0))return;const entry={type:'Deposit',gross,rate,vault,spend,time:Date.now()};entry.audit=audit(entry);state.vaulted=round(state.vaulted+vault);state.spendable=round(state.spendable+spend);state.tx.push(entry);save();render()};
$('#spend').onclick=()=>{const gross=40,baseRate=(+$('#rate').value||0)/100,rate=applies($('#trigger').value,'spend')?baseRate:0,vault=round(gross*rate),total=round(gross+vault);if(state.spendable+0.001<total)return alert('This $40 purchase needs '+money(total)+' available because '+money(vault)+' also moves to your Vault.');const entry={type:'Purchase',gross,amount:gross,rate,vault,spend:total,time:Date.now()};entry.audit=audit(entry);state.spendable=round(state.spendable-total);state.vaulted=round(state.vaulted+vault);state.tx.push(entry);save();render()};
$('#reset').onclick=()=>{state=emptyState();save();render()};
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});syncLabels();